### ISSUE TITLE
相册增加图片失败，再次打开该相册报错

### ISSUE THREAD

**Issue by gavinchan2046** [xupingmao/xnote#7]
相册增加图片失败，再次打开该相册报错，想删除都删除不掉

```
<type 'exceptions.TypeError'> at /note/00000001580738895682
must be type, not classobj
Python	/root/xnote-2.4/handlers/note/view.py in GET, line 241
Web	GET http://192.168.1.7:9100/note/00000001580738895682
Traceback (innermost first)
/root/xnote-2.4/handlers/note/view.py in GET
        return super(ViewByIdHandler, self).GET("view", id) ...
▼ Local vars
Variable	Value
id	
u'00000001580738895682'
self	
<handlers.note.view.ViewByIdHandler instance at 0x7f1c101ccfc8>
core/xmanager.py in GET
            result = wrap(self.target.GET(*args)) ...
▼ Local vars
Variable	Value
WrappedHandler	
<class xmanager.WrappedHandler at 0x7f1c10120a78>
args	
(u'00000001580738895682',)
self	
<xmanager.WrappedHandler instance at 0x7f1c101cc7a0>
wrap	
<function wrap at 0x7f1c1012c5f0>
lib/web/application.py in handle_class
            return tocall(*args) ...
▼ Local vars
Variable	Value
args	
[u'00000001580738895682']
cls	
<class xmanager.WrappedHandler at 0x7f1c10120a78>
meth	
u'GET'
tocall	
<bound method WrappedHandler.GET of <xmanager.WrappedHandler instance at 0x7f1c101cc7a0>>
lib/web/application.py in _delegate
            return handle_class(f) ...
▼ Local vars
Variable	Value
args	
[u'00000001580738895682']
f	
<class xmanager.WrappedHandler at 0x7f1c10120a78>
fvars	
{'handlers_api_check_network': <class handlers.api.check_network.handler at 0x7f1c1019f1f0>, 'handlers_api_getip': <class handlers.api.getip.handler at 0x7f1c1019f2c0>, 'handlers_api_http_headers': <class handlers.api.http_headers.handler at 0x7f1c1019f460>, 'handlers_api_ipv6': <class handlers.api.ipv6.handler at 0x7f1c1019f598>, 'handlers_api_readbook': <class handlers.api.readbook.handler at 0x7f1c145a2a10>, 'handlers_api_report_time': <class handlers.api.report_time.handler at 0x7f1c10090738>, 'handlers_api_report_weather': <class handlers.api.report_weather.handler at 0x7f1c100908d8>, 'handlers_api_tts': <class handlers.api.tts.handler at 0x7f1c10090a10>, 'handlers_code_lines': <class handlers.code.lines.handler at 0x7f1c100b4460>, 'handlers_login': <class handlers.login.handler at 0x7f1c146778d8>, 'handlers_logout': <class handlers.logout.handler at 0x7f1c10295120>, 'handlers_system_backup': <class handlers.system.backup.handler at 0x7f1c10090188>, 'handlers_system_exception': <class 'handlers.system.exception.handler'>, 'handlers_system_handler_profile': <class handlers.system.handler_profile.handler at 0x7f1c100b4a10>, 'handlers_system_network_profile': <class handlers.system.network_profile.handler at 0x7f1c14568ce8>, 'handlers_system_template_cache': <class handlers.system.template_cache.handler at 0x7f1bd3be17a0>, 'handlers_system_thread_info': <class handlers.system.thread_info.handler at 0x7f1bd3dce188>, 'handlers_tools_notebook': <class handlers.tools.notebook.handler at 0x7f1bd3dce2c0>, 'handlers_tools_sql': <class handlers.tools.sql.handler at 0x7f1bd3dce6d0>}
handle_class	
<function handle_class at 0x7f1c10085488>
self	
<web.application.application instance at 0x7f1c153b1368>
lib/web/application.py in handle
        return self._delegate(fn, self.fvars, args) ...
▼ Local vars
Variable	Value
args	
[u'00000001580738895682']
fn	
<class xmanager.WrappedHandler at 0x7f1c10120a78>
self	
<web.application.application instance at 0x7f1c153b1368>
lib/web/application.py in process
                    return self.handle() ...
▼ Local vars
Variable	Value
process	
<function process at 0x7f1c10085398>
processors	
[]
self	
<web.application.application instance at 0x7f1c153b1368>
Request information
INPUT
No data.

COOKIES
Variable	Value
compact_display_state	
'false'
filter	
'all'
xpass	
'0a38bf8d84617810ca0a7e8cb386795c'
xuser	
'gavin'
META
Variable	Value
app_stack	
[<web.application.application instance at 0x7f1c153b1368>]
fullpath	
u'/note/00000001580738895682'
headers	
[]
home	
u'http://192.168.1.7:9100'
homedomain	
u'http://192.168.1.7:9100'
homepath	
u''
host	
u'192.168.1.7:9100'
ip	
u'192.168.1.106'
method	
u'GET'
output	
u''
path	
u'/note/00000001580738895682'
protocol	
u'http'
query	
u''
realhome	
u'http://192.168.1.7:9100'
status	
'200 OK'
ENVIRONMENT
Variable	Value
ACTUAL_SERVER_PROTOCOL	
'HTTP/1.1'
HTTP_ACCEPT	
'text/html,application/xhtml+xml,application/xml;q=0.9,image/webp,image/apng,*/*;q=0.8,application/signed-exchange;v=b3;q=0.9'
HTTP_ACCEPT_ENCODING	
'gzip, deflate'
HTTP_ACCEPT_LANGUAGE	
'zh-CN,zh;q=0.9,en-GB;q=0.8,en;q=0.7,zh-TW;q=0.6'
HTTP_CONNECTION	
'keep-alive'
HTTP_COOKIE	
'filter=all; compact_display_state=false; xuser=gavin; xpass=0a38bf8d84617810ca0a7e8cb386795c'
HTTP_HOST	
'192.168.1.7:9100'
HTTP_REFERER	
'http://192.168.1.7:9100/note/gallery'
HTTP_UPGRADE_INSECURE_REQUESTS	
'1'
HTTP_USER_AGENT	
'Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/79.0.3945.130 Safari/537.36'
PATH_INFO	
'/note/00000001580738895682'
QUERY_STRING	
''
REMOTE_ADDR	
'192.168.1.106'
REMOTE_PORT	
'13456'
REQUEST_METHOD	
'GET'
REQUEST_URI	
'/note/00000001580738895682'
SCRIPT_NAME	
''
SERVER_NAME	
'localhost'
SERVER_PORT	
'9100'
SERVER_PROTOCOL	
'HTTP/1.1'
SERVER_SOFTWARE	
'CherryPy/unknown Server'
wsgi.errors	
<open file '<stderr>', mode 'w' at 0x7f1c234a31e0>
wsgi.input	
<web.wsgiserver.wsgiserver2.KnownLengthRFile object at 0x7f1c14669610>
wsgi.multiprocess	
False
wsgi.multithread	
True
wsgi.run_once	
False
wsgi.url_scheme	
'http'
wsgi.version	
(1, 0)
You're seeing this error because you have web.config.debug set to True. Set that to False if you don't want to see this.
```

**Comment by xupingmao** [comment]
升级到最新版看看能不能解决问题，相册工具栏的管理按钮可以删除图片。

**Comment by gavinchan2046** [comment]
git clone最新版本，启动报错。
已 pip requirement.txt，firewall-cmd开9100端口， python 3.8.1
```
[root@centos7 xnote]# python app.py --port 9100
Traceback (most recent call last):
  File "app.py", line 37, in <module>
    import xmanager
  File "core/xmanager.py", line 25, in <module>
    import xtemplate
  File "core/xtemplate.py", line 12, in <module>
    import xauth
  File "core/xauth.py", line 8, in <module>
    from xutils import ConfigParser, textutil, dbutil, fsutil
  File "/root/xnote/xutils/dbutil.py", line 15, in <module>
    import leveldb
SystemError: bad call flags
```

**Comment by xupingmao** [comment]
之前的leveldb库版本不支持python3.8，已经升级到了最新版。py3.8测试通过。

请把xnote升级到最新版试试。

**Comment by gavinchan2046** [comment]
升级最新代码，pip requirement.txt 后OK了， 感谢！
